# bone_test_panic.py
# "Panic is just a state of high conductivity."

import time
from bone_main import BoneAmanita
from bone_bus import Prisma, BoneConfig, CycleContext, PhysicsPacket
from bone_cycle import IntrusionPhase, NavigationPhase, SensationPhase

def run_phase_simulation(eng, ctx, phase_class):
    """Runs a specific phase in isolation with the given context."""
    phase = phase_class(eng)
    return phase.run(ctx)

def run_panic_simulation():
    print(f"{Prisma.paint('>>> INITIATING PANIC PROTOCOL', 'R')}")

    # 1. Boot the Engine
    eng = BoneAmanita(user_name="TEST_SUBJECT_01")
    print(f"{Prisma.paint('System Booted. Vital signs stable.', 'G')}")

    # ==============================================================================
    # TEST 1: THE IMMUNE SYSTEM (Viral Tracer)
    # Goal: Force 'Narrative Drag' high and inject a loop to see if the Tracer fires.
    # ==============================================================================
    print(f"\n{Prisma.paint('--- TEST 1: AUTOIMMUNE RESPONSE ---', 'Y')}")

    # Construct Context with HIGH DRAG (Trigger)
    ctx = CycleContext(input_text="void void void")
    ctx.clean_words = ["void", "nothing"] # Ruminative words
    ctx.physics = PhysicsPacket(
        narrative_drag=10.0, # ARTIFICIAL STRESS
        kappa=0.1,
        counts={"abstract": 5}
    )

    # Prime the Memory Graph
    eng.mind.mem.graph = {
        "void": {"edges": {"nothing": 5}, "last_tick": 0},
        "nothing": {"edges": {"void": 5}, "last_tick": 0}
    }

    # Run Intrusion Phase
    ctx = run_phase_simulation(eng, ctx, IntrusionPhase)

    # Check Logs
    immune_log = next((l for l in ctx.logs if "IMMUNE SYSTEM" in l), None)
    if immune_log:
        print(f"{Prisma.paint('✔ SUCCESS:', 'G')} Immune System fired: {immune_log}")
    else:
        print(f"{Prisma.paint('✘ FAILURE:', 'R')} Immune system remained dormant.")

    # ==============================================================================
    # TEST 2: THE UNIFIED MAP (Navigator Authority)
    # Goal: Ensure physics doesn't hallucinate a location. Navigator decides.
    # ==============================================================================
    print(f"\n{Prisma.paint('--- TEST 2: SPATIAL CONSISTENCY ---', 'Y')}")

    # Construct Context with HIGH VOLTAGE (The Forge)
    ctx = CycleContext(input_text="burn burn burn")
    ctx.physics = PhysicsPacket(
        voltage=18.0,       # High Energy
        narrative_drag=-1.0, # Zero Friction
        clean_words=["fire", "spark", "iron"],
        vector={"VEL": 0.9, "ENT": 0.8}
    )

    # Run Navigation Phase
    # Note: Navigator relies on engine state, so we update the context and engine
    eng.phys.tension.last_physics_packet = ctx.physics # Sync engine state
    ctx = run_phase_simulation(eng, ctx, NavigationPhase)

    current_loc = eng.navigator.current_location
    print(f"Physics Vectors: Voltage=18.0, Drag=-1.0")
    print(f"Navigator reports: {current_loc}")

    if current_loc == "THE_FORGE":
        print(f"{Prisma.paint('✔ SUCCESS:', 'G')} Location aligns with Voltage/Drag map.")
    else:
        print(f"{Prisma.paint('⚠ WARNING:', 'O')} Location drift detected ({current_loc}).")

    # ==============================================================================
    # TEST 3: THE SYNESTHETIC BRIDGE (Body-Mind Link)
    # Goal: Ensure the 'Somatic Reflex' generated by biology appears in the UI.
    # ==============================================================================
    print(f"\n{Prisma.paint('--- TEST 3: SOMATIC ALIGNMENT ---', 'Y')}")

    # Spike Adrenaline (Biology) and Voltage (Physics)
    ctx = CycleContext(input_text="run run run")
    ctx.physics = PhysicsPacket(voltage=16.0, valence=-0.8)
    eng.bio.endo.adrenaline = 0.9 # Body is racing

    # Run Sensation Phase
    ctx = run_phase_simulation(eng, ctx, SensationPhase)

    # Check Context for Impulse
    impulse = getattr(ctx, "last_impulse", None)

    if impulse and "Dilating" in impulse.somatic_reflex:
        print(f"Somatic Reflex: {impulse.somatic_reflex}")
        print(f"{Prisma.paint('✔ SUCCESS:', 'G')} The Mind felt the Body's reflex.")
    else:
        val = impulse.somatic_reflex if impulse else "None"
        print(f"{Prisma.paint('✘ FAILURE:', 'R')} Sensation mismatch. Got: {val}")

    print(f"\n{Prisma.paint('>>> PANIC SIMULATION COMPLETE', 'W')}")

if __name__ == "__main__":
    run_panic_simulation()